-- USERS (minimal data + OAuth identifier)
CREATE TABLE users (
  id UUID PRIMARY KEY,                -- generated by app
  username TEXT,
  email TEXT UNIQUE
);

CREATE INDEX idx_users_provider_account ON users(provider, provider_account_id);