-- +goose Up
-- POSTS (Markdown as canonical source; no excerpt or cache)
CREATE TABLE posts (
  id UUID PRIMARY KEY,                -- generated by app
  author_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  slug TEXT UNIQUE,                   -- optional for URLs
  raw_markdown TEXT NOT NULL,         -- canonical source (includes URLs to images/embeds)
  published_at TIMESTAMPTZ,           -- NULL if draft
  created_at TIMESTAMPTZ NOT NULL,    -- generated by app
  updated_at TIMESTAMPTZ NOT NULL     -- generated by app
);

CREATE INDEX idx_posts_author ON posts(author_id);
CREATE INDEX idx_posts_published_at ON posts(published_at);

-- +goose Down
DROP INDEX IF EXISTS idx_posts_published_at;
DROP INDEX IF EXISTS idx_posts_author;
DROP TABLE IF EXISTS posts;