-- COMMENTS (simple text, supports replies with parent_id)
CREATE TABLE comments (
  id UUID PRIMARY KEY,               -- generated by app
  post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  parent_id UUID REFERENCES comments(id) ON DELETE CASCADE, -- NULL if root
  body TEXT NOT NULL,                -- markdown allowed
  created_at TIMESTAMPTZ NOT NULL,   -- generated by app
  updated_at TIMESTAMPTZ NOT NULL    -- generated by app
);

CREATE INDEX idx_comments_post ON comments(post_id);
CREATE INDEX idx_comments_parent ON comments(parent_id);