-- +goose Up
-- LIKES (only for posts; one like per user + post)
CREATE TABLE post_likes (
  id UUID PRIMARY KEY,               -- generated by app
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (user_id, post_id)
);

CREATE INDEX idx_post_likes_post ON post_likes(post_id);
CREATE INDEX idx_post_likes_user ON post_likes(user_id);

-- +goose Down
DROP INDEX IF EXISTS idx_post_likes_user;
DROP INDEX IF EXISTS idx_post_likes_post;
DROP TABLE IF EXISTS post_likes;