-- +goose Up
-- BOOKMARKS / FAVORITES (user bookmarks a post)
CREATE TABLE bookmarks (
  id UUID PRIMARY KEY,               -- generated by app
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL,
  UNIQUE (user_id, post_id)
);

CREATE INDEX idx_bookmarks_user ON bookmarks(user_id);

-- +goose Down
DROP INDEX IF EXISTS idx_bookmarks_user;
DROP TABLE IF EXISTS bookmarks;